### ISSUE TITLE
You can work with Bluesky threads using Python SDK

### ISSUE THREAD

**Issue by MarshalX** [weiwei/dufu#1]
> For now it only posts shorter poems. Longer ones will exceed the 300 char limit will be supported when the SDK supports threads

Hi, I found this note about SDK. You can reply to the root post again and again building the chain of the posts to exceed 300 symbols per post. Here is an example of how to work with replies: https://github.com/MarshalX/atproto/blob/main/examples/send_reply.py

**Comment by MarshalX** [comment]
as i can see it was resolved in https://github.com/weiwei/dufu/commit/f3f5583f8d8f7c696350f4ddf4d030cdb69f9da0

**Comment by weiwei** [comment]
Somehow I missed this message. Thanks @MarshalX for your wonderful package!
